export interface FeatureDefinition {
  key: string;
  label: string;
  unit?: string;
  description: string;
  defaultValue: number;
  min?: number;
  max?: number;
  step?: number;
  category: 'core' | 'advanced';
  isEngineered?: boolean;
}

// 14 Core Network Flow Features
export const CORE_FEATURES: FeatureDefinition[] = [
  {
    key: 'Destination Port',
    label: 'Destination Port',
    unit: 'port',
    description: 'Target service port on destination host (e.g. 80, 443, 22, 53)',
    defaultValue: 80,
    min: 0,
    max: 65535,
    step: 1,
    category: 'core',
  },
  {
    key: 'Flow Duration',
    label: 'Flow Duration',
    unit: 'µs',
    description: 'Total duration of the network flow in microseconds',
    defaultValue: 31060,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Total Fwd Packets',
    label: 'Total Fwd Packets',
    unit: 'pkts',
    description: 'Total number of packets transmitted in forward direction',
    defaultValue: 2,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Total Backward Packets',
    label: 'Total Backward Packets',
    unit: 'pkts',
    description: 'Total number of packets received in backward direction',
    defaultValue: 2,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Total Length of Fwd Packets',
    label: 'Total Length of Fwd Packets',
    unit: 'bytes',
    description: 'Total size of payload in forward direction',
    defaultValue: 138,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Total Length of Bwd Packets',
    label: 'Total Length of Bwd Packets',
    unit: 'bytes',
    description: 'Total size of payload in backward direction',
    defaultValue: 586,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Fwd Packet Length Max',
    label: 'Fwd Packet Length Max',
    unit: 'bytes',
    description: 'Maximum packet length observed in forward direction',
    defaultValue: 69,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Fwd Packet Length Min',
    label: 'Fwd Packet Length Min',
    unit: 'bytes',
    description: 'Minimum packet length observed in forward direction',
    defaultValue: 69,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Fwd Packet Length Mean',
    label: 'Fwd Packet Length Mean',
    unit: 'bytes',
    description: 'Mean packet length in forward direction',
    defaultValue: 69,
    min: 0,
    step: 0.1,
    category: 'core',
  },
  {
    key: 'Fwd Packet Length Std',
    label: 'Fwd Packet Length Std',
    unit: 'bytes',
    description: 'Standard deviation of packet length in forward direction',
    defaultValue: 0,
    min: 0,
    step: 0.1,
    category: 'core',
  },
  {
    key: 'Bwd Packet Length Max',
    label: 'Bwd Packet Length Max',
    unit: 'bytes',
    description: 'Maximum packet length observed in backward direction',
    defaultValue: 293,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Bwd Packet Length Min',
    label: 'Bwd Packet Length Min',
    unit: 'bytes',
    description: 'Minimum packet length observed in backward direction',
    defaultValue: 293,
    min: 0,
    step: 1,
    category: 'core',
  },
  {
    key: 'Bwd Packet Length Mean',
    label: 'Bwd Packet Length Mean',
    unit: 'bytes',
    description: 'Mean packet length in backward direction',
    defaultValue: 293,
    min: 0,
    step: 0.1,
    category: 'core',
  },
  {
    key: 'Bwd Packet Length Std',
    label: 'Bwd Packet Length Std',
    unit: 'bytes',
    description: 'Standard deviation of packet length in backward direction',
    defaultValue: 0,
    min: 0,
    step: 0.1,
    category: 'core',
  },
];

// Advanced & Engineered Features matching backend schema
export const ADVANCED_FEATURES: FeatureDefinition[] = [
  { key: 'Flow Bytes/s', label: 'Flow Bytes/s', unit: 'B/s', description: 'Flow throughput in bytes per second', defaultValue: 23309.72, category: 'advanced' },
  { key: 'Flow Packets/s', label: 'Flow Packets/s', unit: 'P/s', description: 'Flow packet rate', defaultValue: 128.78, category: 'advanced' },
  { key: 'Flow IAT Mean', label: 'Flow IAT Mean', unit: 'µs', description: 'Mean inter-arrival time of flow', defaultValue: 10353.33, category: 'advanced' },
  { key: 'Flow IAT Std', label: 'Flow IAT Std', unit: 'µs', description: 'Standard deviation of inter-arrival time', defaultValue: 17926.43, category: 'advanced' },
  { key: 'Flow IAT Max', label: 'Flow IAT Max', unit: 'µs', description: 'Maximum inter-arrival time', defaultValue: 31053.0, category: 'advanced' },
  { key: 'Flow IAT Min', label: 'Flow IAT Min', unit: 'µs', description: 'Minimum inter-arrival time', defaultValue: 3.0, category: 'advanced' },
  { key: 'Fwd IAT Total', label: 'Fwd IAT Total', unit: 'µs', description: 'Total forward inter-arrival time', defaultValue: 3.0, category: 'advanced' },
  { key: 'Fwd IAT Mean', label: 'Fwd IAT Mean', unit: 'µs', description: 'Mean forward inter-arrival time', defaultValue: 3.0, category: 'advanced' },
  { key: 'Fwd IAT Std', label: 'Fwd IAT Std', unit: 'µs', description: 'Std dev of forward inter-arrival time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Fwd IAT Max', label: 'Fwd IAT Max', unit: 'µs', description: 'Max forward inter-arrival time', defaultValue: 3.0, category: 'advanced' },
  { key: 'Fwd IAT Min', label: 'Fwd IAT Min', unit: 'µs', description: 'Min forward inter-arrival time', defaultValue: 3.0, category: 'advanced' },
  { key: 'Bwd IAT Total', label: 'Bwd IAT Total', unit: 'µs', description: 'Total backward inter-arrival time', defaultValue: 4.0, category: 'advanced' },
  { key: 'Bwd IAT Mean', label: 'Bwd IAT Mean', unit: 'µs', description: 'Mean backward inter-arrival time', defaultValue: 4.0, category: 'advanced' },
  { key: 'Bwd IAT Std', label: 'Bwd IAT Std', unit: 'µs', description: 'Std dev of backward inter-arrival time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Bwd IAT Max', label: 'Bwd IAT Max', unit: 'µs', description: 'Max backward inter-arrival time', defaultValue: 4.0, category: 'advanced' },
  { key: 'Bwd IAT Min', label: 'Bwd IAT Min', unit: 'µs', description: 'Min backward inter-arrival time', defaultValue: 4.0, category: 'advanced' },
  { key: 'Fwd PSH Flags', label: 'Fwd PSH Flags', description: 'Forward PSH flag counter', defaultValue: 0.0, category: 'advanced' },
  { key: 'Fwd URG Flags', label: 'Fwd URG Flags', description: 'Forward URG flag counter', defaultValue: 0.0, category: 'advanced' },
  { key: 'Fwd Header Length', label: 'Fwd Header Length', unit: 'bytes', description: 'Forward packet header total length', defaultValue: 64.0, category: 'advanced' },
  { key: 'Bwd Header Length', label: 'Bwd Header Length', unit: 'bytes', description: 'Backward packet header total length', defaultValue: 64.0, category: 'advanced' },
  { key: 'Fwd Packets/s', label: 'Fwd Packets/s', unit: 'P/s', description: 'Forward packets per second', defaultValue: 64.39, category: 'advanced' },
  { key: 'Bwd Packets/s', label: 'Bwd Packets/s', unit: 'P/s', description: 'Backward packets per second', defaultValue: 64.39, category: 'advanced' },
  { key: 'Min Packet Length', label: 'Min Packet Length', unit: 'bytes', description: 'Minimum overall packet length', defaultValue: 69.0, category: 'advanced' },
  { key: 'Max Packet Length', label: 'Max Packet Length', unit: 'bytes', description: 'Maximum overall packet length', defaultValue: 293.0, category: 'advanced' },
  { key: 'Packet Length Mean', label: 'Packet Length Mean', unit: 'bytes', description: 'Mean overall packet length', defaultValue: 158.6, category: 'advanced' },
  { key: 'Packet Length Std', label: 'Packet Length Std', unit: 'bytes', description: 'Standard deviation of packet length', defaultValue: 122.69, category: 'advanced' },
  { key: 'Packet Length Variance', label: 'Packet Length Variance', description: 'Variance of packet length', defaultValue: 15052.8, category: 'advanced' },
  { key: 'FIN Flag Count', label: 'FIN Flag Count', description: 'FIN control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'SYN Flag Count', label: 'SYN Flag Count', description: 'SYN control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'RST Flag Count', label: 'RST Flag Count', description: 'RST control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'PSH Flag Count', label: 'PSH Flag Count', description: 'PSH control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'ACK Flag Count', label: 'ACK Flag Count', description: 'ACK control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'URG Flag Count', label: 'URG Flag Count', description: 'URG control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'ECE Flag Count', label: 'ECE Flag Count', description: 'ECE control flag count', defaultValue: 0.0, category: 'advanced' },
  { key: 'Down/Up Ratio', label: 'Down/Up Ratio', description: 'Download to upload ratio', defaultValue: 1.0, category: 'advanced' },
  { key: 'Average Packet Size', label: 'Average Packet Size', unit: 'bytes', description: 'Average packet payload size', defaultValue: 198.25, category: 'advanced' },
  { key: 'Init_Win_bytes_forward', label: 'Init Win Bytes Fwd', description: 'TCP Initial Window size forward', defaultValue: 1024.0, category: 'advanced' },
  { key: 'Init_Win_bytes_backward', label: 'Init Win Bytes Bwd', description: 'TCP Initial Window size backward', defaultValue: 235.0, category: 'advanced' },
  { key: 'act_data_pkt_fwd', label: 'Act Data Pkt Fwd', description: 'Count of forward packets with payload data', defaultValue: 1.0, category: 'advanced' },
  { key: 'min_seg_size_forward', label: 'Min Seg Size Forward', description: 'Minimum segment size observed forward', defaultValue: 32.0, category: 'advanced' },
  { key: 'Active Mean', label: 'Active Mean', unit: 'µs', description: 'Mean active time before idle', defaultValue: 0.0, category: 'advanced' },
  { key: 'Active Std', label: 'Active Std', unit: 'µs', description: 'Standard deviation of active time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Active Max', label: 'Active Max', unit: 'µs', description: 'Max active time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Active Min', label: 'Active Min', unit: 'µs', description: 'Min active time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Idle Mean', label: 'Idle Mean', unit: 'µs', description: 'Mean idle duration between flow bursts', defaultValue: 0.0, category: 'advanced' },
  { key: 'Idle Std', label: 'Idle Std', unit: 'µs', description: 'Standard deviation of idle time', defaultValue: 0.0, category: 'advanced' },
  { key: 'Idle Max', label: 'Idle Max', unit: 'µs', description: 'Max idle duration', defaultValue: 0.0, category: 'advanced' },
  { key: 'Idle Min', label: 'Idle Min', unit: 'µs', description: 'Min idle duration', defaultValue: 0.0, category: 'advanced' },
  // Engineered Ratios & Features for CYVORA Rare Attack Optimization
  { key: 'Fwd_Bwd_Length_Ratio', label: 'Fwd/Bwd Length Ratio', description: 'Ratio of forward to backward byte length', defaultValue: 0.2368, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Bwd_Packet_Ratio', label: 'Fwd/Bwd Packet Ratio', description: 'Ratio of forward to backward packet count', defaultValue: 1.0, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Bwd_Length_Mean_Ratio', label: 'Fwd/Bwd Length Mean Ratio', description: 'Ratio of mean forward/backward packet size', defaultValue: 0.2381, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Bwd_Length_Max_Ratio', label: 'Fwd/Bwd Length Max Ratio', description: 'Ratio of max forward/backward packet size', defaultValue: 0.2381, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Packet_Length_Range', label: 'Fwd Packet Length Range', description: 'Max - Min forward packet length', defaultValue: 0.0, category: 'advanced', isEngineered: true },
  { key: 'Bwd_Packet_Length_Range', label: 'Bwd Packet Length Range', description: 'Max - Min backward packet length', defaultValue: 0.0, category: 'advanced', isEngineered: true },
  { key: 'Packets_Per_Duration', label: 'Packets Per Duration', description: 'Normalized packet count over duration', defaultValue: 1332.09, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Bwd_IAT_Ratio', label: 'Fwd/Bwd IAT Ratio', description: 'Ratio of forward to backward inter-arrival times', defaultValue: 0.8, category: 'advanced', isEngineered: true },
  { key: 'Flow_IAT_Variability', label: 'Flow IAT Variability', description: 'Coefficient of variability of flow IAT', defaultValue: 1.7313, category: 'advanced', isEngineered: true },
  { key: 'SYN_ACK_Ratio', label: 'SYN/ACK Ratio', description: 'Ratio of SYN flags to ACK flags', defaultValue: 1.0, category: 'advanced', isEngineered: true },
  { key: 'PSH_ACK_Ratio', label: 'PSH/ACK Ratio', description: 'Ratio of PSH flags to ACK flags', defaultValue: 1.0, category: 'advanced', isEngineered: true },
  { key: 'FIN_RST_Ratio', label: 'FIN/RST Ratio', description: 'Ratio of FIN flags to RST flags', defaultValue: 1.0, category: 'advanced', isEngineered: true },
  { key: 'Window_Size_Ratio', label: 'Window Size Ratio', description: 'Ratio of forward to backward window size', defaultValue: 4.3432, category: 'advanced', isEngineered: true },
  { key: 'Window_Size_Difference', label: 'Window Size Difference', description: 'Absolute difference in initial TCP windows', defaultValue: 789.0, category: 'advanced', isEngineered: true },
  { key: 'Packet_Length_CV', label: 'Packet Length CV', description: 'Coefficient of variation of packet length', defaultValue: 0.7687, category: 'advanced', isEngineered: true },
  { key: 'Fwd_Header_Payload_Ratio', label: 'Fwd Header/Payload Ratio', description: 'Forward header overhead ratio', defaultValue: 0.4676, category: 'advanced', isEngineered: true },
  { key: 'Bwd_Header_Payload_Ratio', label: 'Bwd Header/Payload Ratio', description: 'Backward header overhead ratio', defaultValue: 0.1107, category: 'advanced', isEngineered: true },
  { key: 'Flow Duration_log', label: 'Flow Duration (Log)', description: 'Log-transformed flow duration', defaultValue: 10.3437, category: 'advanced', isEngineered: true },
  { key: 'Total Length of Fwd Packets_log', label: 'Fwd Length (Log)', description: 'Log-transformed forward packet length', defaultValue: 4.9345, category: 'advanced', isEngineered: true },
  { key: 'Total Length of Bwd Packets_log', label: 'Bwd Length (Log)', description: 'Log-transformed backward packet length', defaultValue: 6.3750, category: 'advanced', isEngineered: true },
  { key: 'Flow Packets/s_log', label: 'Flow Packets/s (Log)', description: 'Log-transformed packet rate', defaultValue: 4.8659, category: 'advanced', isEngineered: true },
  { key: 'Fwd Packets/s_log', label: 'Fwd Packets/s (Log)', description: 'Log-transformed forward packet rate', defaultValue: 4.1804, category: 'advanced', isEngineered: true },
  { key: 'Bwd Packets/s_log', label: 'Bwd Packets/s (Log)', description: 'Log-transformed backward packet rate', defaultValue: 4.1804, category: 'advanced', isEngineered: true },
  { key: 'Init_Win_bytes_forward_log', label: 'Fwd Win Bytes (Log)', description: 'Log-transformed forward TCP window', defaultValue: 6.9324, category: 'advanced', isEngineered: true },
  { key: 'Init_Win_bytes_backward_log', label: 'Bwd Win Bytes (Log)', description: 'Log-transformed backward TCP window', defaultValue: 5.4638, category: 'advanced', isEngineered: true },
];

export const ALL_FEATURES: FeatureDefinition[] = [...CORE_FEATURES, ...ADVANCED_FEATURES];

export const getDefaultFeaturePayload = (): Record<string, number> => {
  const payload: Record<string, number> = {};
  ALL_FEATURES.forEach((feature) => {
    payload[feature.key] = feature.defaultValue;
  });
  return payload;
};
